package main

import (
	"flag"
	"log"
)

type quizOptions struct {
	filePath *string
	quantity *int
	level    *int
}

type quizTask struct {
	question string
	answer   string
}

func main() {
	options := quizOptions{}
	loadFlagOptions(&options)
	tasks := prepareQuiz(options)
	runQuiz(tasks, options)
}

func loadFlagOptions(options *quizOptions) {
	options.filePath = flag.String("file", "", "CSV file containing tasks for quiz. Format must be 'task,answer'. If not passed, random tasks will be generated by the program.")
	options.quantity = flag.Int("quantity", 10, "Number of tasks per session")
	options.level = flag.Int("level", 1, "Level is considered only when generating tasks. Number of level basically corresponds to number of digits in numbers used for tasks. Max level is 4, if passed higher number, it will be defaulted to 1.  Example: choosing level 2 may generate numbers between 10 and 100 (not including 100) for your tasks.")
	flag.Parse()
}

func prepareQuiz(options quizOptions) []quizTask {
	if *options.filePath != "" {
		return readTasks(*options.filePath)
	}

	if *options.level > 4 {
		*options.level = 1
	}

	tasks := generateTasks(options)
	log.Printf("Generated tasks (level %d) saved to '%s', feel free to check them out later on (or cheat, no one will know 😉 )!", *options.level, saveTasks(tasks))
	return tasks
}

func checkErr(err error, msg string) {
	if err != nil {
		log.Print(msg)
	}
}

func checkFatalErr(err error, msg string) {
	if err != nil {
		log.Fatal(msg)
	}
}
